---
title: "Draft-Cleaning/EDA"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(magrittr)
library(readr)
library(lubridate)
library(ggthemes)
```

```{r message=FALSE, warning=FALSE}
bjl <- read_csv('BJlistings.csv')
bjr <- read_csv('BJreviews.csv')
bjc <- read_csv('BJcalendar.csv')

bosl <- read_csv('Boslistings.csv')
bosr <- read_csv('Bosreviews.csv')
bosc <- read_csv('Boscalendar.csv')
```

### Primary Variables Removal 

1. remove non neccessary and repeated columns

```{r}
dim(bjl);dim(bosl)

# step 1
# remove all url, which are NAs
bosl2 <- bosl %>% select(-ends_with("_url"), -experiences_offered,
                     -host_total_listings_count,-calendar_last_scraped,
                     -country)

bjl2 <- bjl %>% select(-ends_with("_url"), -experiences_offered,
                     -host_total_listings_count,-calendar_last_scraped,
                     -country)
dim(bosl2);dim(bjl2)
# step 2
# remove needless columns
bjl2 <- bjl2[ ,-c(2:3)]
bosl2 <- bosl2[,-c(2:3)]
dim(bosl2);dim(bjl2)

# step 3
# remove columns with over 60% NA observations
bjl3 <- bjl2[, -which(colMeans(is.na(bjl2)) > 0.8)]
bosl3<- bosl2[, -which(colMeans(is.na(bosl2)) > 0.6)]
dim(bjl3);dim(bosl3)

# View the columns we removed for step3
b <- apply(bosl2, 2, function(col)sum(is.na(col))/length(col))
b[b>0.6]

c <- apply(bjl2, 2, function(col)sum(is.na(col))/length(col))
c[c>0.8]


# step 3 removed for beijing & boston listing: neighbourhood_group_cleansed, square_feet, weekly_price, monthly_price

# special removal only for beijingllisting: license, jurisdiction_names 

# though high NA rate but will not be directly removed for beijing listing:
# cleaning_fee,security_deposit (over 60% NA rate)
```

2. remove $ sign for `security_deposit`, `price`, and `cleaning_fee`
```{r}
# eliminate $ sign 

bjl3$security_deposit = as.numeric(gsub("\\$", "", bjl3$security_deposit))
bjl3$price <- as.numeric(gsub("\\$", "", bjl3$price))
bjl3$cleaning_fee = as.numeric(gsub("\\$", "", bjl3$cleaning_fee))

bosl3$security_deposit = as.numeric(gsub("\\$", "", bosl3$security_deposit))
bosl3$price <- as.numeric(gsub("\\$", "", bosl3$price))
bosl3$cleaning_fee = as.numeric(gsub("\\$", "", bosl3$cleaning_fee))

# $ sign in calendar data
dim(bosc);dim(bjc)
bosc$price <- as.numeric(gsub("\\$", "", bosc$price))
bjc$price <- as.numeric(gsub("\\$", "", bjc$price))

summary(bosc$price)
summary(bjc$price)
```

3. remove % sign for `host_response_rate` 

```{r}
bosl3$host_response_rate <- sapply(bosl3$host_response_rate, 
                                  function(x) gsub('%','',x))
bjl3$host_response_rate <- sapply(bjl3$host_response_rate, 
                                  function(x) gsub('%','',x))
```

4. Create current time format for reviews and calendar data
```{r}
# timestamp clean into lubricate version for reviews of boston and beijing
bosr$date <- ymd(bosr$date)
bosr$year <- year(bosr$date)
bjr$date <- ymd(bjr$date)
bjr$year <- year(bjr$date)
bosr$wkd <- wday(bosr$date,label = TRUE)
bjr$wkd <- wday(bjr$date, label=TRUE)

bosc$date <- ymd(bosc$date)
bosc$year <- year(bosc$date)
bosc$month <- month(ymd(bosc$date))
bjc$date <- ymd(bjc$date)
bjc$year <- year(bjc$date)
bosc$wkd <- wday(bosc$date,label = TRUE)
bjc$wkd <- wday(bjc$date, label=TRUE)
bjc$month <- month(ymd(bjc$date))

```


### EDA Part 1 


# Graph 1
```{r}
bjyreview <- bjr %>% group_by(year) %>%  count(listing_id) %>% arrange(desc(n)) 
bosyreview <- bosr %>% group_by(year) %>% count(listing_id) %>% arrange(desc(n)) 


# bjl %>% select(id, name, number_of_reviews) %>% arrange(desc(number_of_reviews))
# bjl %>% select(id, name, number_of_reviews) %>% arrange(number_of_reviews)
# 23437 listings have reviews for Beijing
# 23437/38814
#bosl %>% select(id, name, number_of_reviews) %>% #arrange(desc(number_of_reviews))
# 3507 listings have reviews for Boston
# 3507/3585
# the rate of review in boston is higher than beijing 

ggplot(bjyreview,aes(x=as.factor(year),y=n))+
  geom_jitter(alpha=0.3,aes(color=n)) +
  geom_smooth() +
  theme_economist()+
  scale_fill_brewer() +ylim(0,250) +labs(title = 'How popular is Airbnb in Beijing', subtitle = 'Number of reviews received for a single listing over years')

ggplot(bosyreview,aes(x=as.factor(year),y=n))+
  geom_jitter(alpha=0.3,aes(color=n)) +
  geom_smooth() +
  theme_economist()+
  scale_fill_brewer() +ylim(0,250) +
  labs(title = 'How popular is Airbnb in Boston', subtitle = 'Number of reviews received for a single listing over years')


```

# Graph 2

```{r}

bosl4 <- bosl3 %>% filter(!is.na(review_scores_rating))
bosl4 <- bosl3 %>% filter(!is.na(host_is_superhost))
bjl4 <- bjl3 %>% filter(!is.na(review_scores_rating))
bjl4 <- bjl3 %>% filter(!is.na(host_is_superhost))


bosl4$host_response_rate <- as.numeric(bosl4$host_response_rate)
bjl4$host_response_rate <- as.numeric(bjl4$host_response_rate)

summary(bjl4$host_response_rate)
summary(bosl4$host_response_rate)

ggplot(bosl4,aes(x=host_response_rate,y=review_scores_rating)) +
  geom_jitter(aes(color=as.factor(host_is_superhost)),alpha=0.3) +theme_economist() +labs(title = 'Indicators for SuperHost', subtitle = 'Avg. Rating by Response Rate in Boston')

ggplot(bjl4,aes(x=host_response_rate,y=review_scores_rating)) +
  geom_jitter(aes(color=as.factor(host_is_superhost)),alpha=0.3) +theme_economist() +
  labs(title = 'Indicators for SuperHost', subtitle = 'Avg. Rating by Response Rate in Beijing')
```


# Graph 3
```{r}
glimpse(bosc)
dim(bosc)


summary(bosc$year)
 
avgpricebj <- bjc %>% group_by(date, wkd) %>% summarize(avgprice= mean(price,na.rm=T))
avgpricebos <- bosc %>% group_by(date, wkd) %>% summarize(avgprice=mean(price,na.rm=T))
ggplot(avgpricebos, aes(x=wkd, y=avgprice)) + geom_boxplot(na.rm=T) + geom_jitter(alpha=0.2) + theme_economist() + labs(title = 'Price Trends over the weekday & weekends in Boston', subtitle = 'avgprice = Avg. price by day')
ggplot(avgpricebj,aes(x=wkd,y=avgprice)) + geom_boxplot(na.rm=T) + geom_jitter(alpha=0.2) +theme_economist() + labs(title = 'Price Trends over the weekday & weekends in Beijing', subtitle = 'avgprice = Avg. price by day')
```

# Graph 4 

```{r}
# avgpricebj2 <- bjc %>% filter(year==2019) %>% group_by(listing_id, month) %>% summarize(avgprice= mean(price,na.rm=T)) 
# 
# avgpricebos2 <- bosc %>% filter(year==2019) %>% group_by(listing_id, month) %>% summarize(avgprice=mean(price,na.rm=T))
# 
# ggplot(avgpricebos2, aes(x=month, y=avgprice)) + geom_point(na.rm=T) + geom_jitter(alpha=0.2) + theme_economist() + labs(title = 'Price Trends over the month in Boston', subtitle = 'avgprice = Avg. price by listing')

```


# Graph 5
```{r}
library(leaflet)
bosAirbnb <- bosl3 %>% mutate(Log1pPrice = log1p(price),
                            transformed_review = bosl3$review_scores_rating^5)
bosAirbnb0 <- bosAirbnb %>% select(-price, -review_scores_rating)

pal <- colorNumeric(palette = rainbow(6), domain = bosAirbnb$Log1pPrice)

leaflet(data = bosAirbnb0) %>%  addProviderTiles(providers$CartoDB.Positron) %>% addCircleMarkers(~longitude, ~latitude, color = ~pal(Log1pPrice), weight = 1, radius=1.5, fillOpacity = 1, opacity = 1,label = paste("Neighbourhood:", bosAirbnb0$neighbourhood_cleansed)) %>% 
  addLegend("bottomright", pal = pal, values = ~Log1pPrice,
            title = "Log1pPrice",
            opacity = 1)


BJAirbnb <- bjl3 %>% mutate(Log1pPrice = log1p(price),
                                   transformed_review = bjl3$review_scores_rating^5)
BJAirbnb0 <- BJAirbnb %>% select(-price, -review_scores_rating)

pal <- colorNumeric(palette = rainbow(6), domain = BJAirbnb$Log1pPrice)

leaflet(data = BJAirbnb0) %>%  addProviderTiles(providers$CartoDB.Positron) %>% addCircleMarkers(~longitude, ~latitude, color = ~pal(Log1pPrice), weight = 1, radius=1.5, fillOpacity = 1, opacity = 1,
                                                                                               label = paste("Neighbourhood:", BJAirbnb0$neighbourhood_cleansed)) %>% 
  addLegend("bottomright", pal = pal, values = ~Log1pPrice,
            title = "Log1pPrice",
            opacity = 1)



```

